# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

change_num_notes__ <- function(x, y) {
    .Call(`_hvr_change_num_notes__`, x, y)
}

change_num_notes_ <- function(contexts, continuation) {
    .Call(`_hvr_change_num_notes_`, contexts, continuation)
}

