# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosine_similarity <- function(x, y) {
    .Call(`_hvr_cosine_similarity`, x, y)
}

cosine_similarities <- function(vector, vectors) {
    .Call(`_hvr_cosine_similarities`, vector, vectors)
}

#' @export
event_probs <- function(weights, observation_matrix, continuation_matrices, legal) {
    .Call(`_hvr_event_probs`, weights, observation_matrix, continuation_matrices, legal)
}

cost <- function(weights, observation_matrix, continuation_matrices, legal) {
    .Call(`_hvr_cost`, weights, observation_matrix, continuation_matrices, legal)
}

gradient <- function(weights, observation_matrix, continuation_matrices, legal) {
    .Call(`_hvr_gradient`, weights, observation_matrix, continuation_matrices, legal)
}

